name: zero2prod
region: nyc
services:
- dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: sesim-nov/zero2prod
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xxs
  name: zero2prod
  routes:
  - path: /
  source_dir: /
