//! Zero2Prod: My implementation of the code from the Zero to Production Book
//!
//! This codebase implements the REST API generated by working through the book Zero to Production,
//! by Luca Palmieri.
pub mod configuration;
pub mod domain;
pub mod mail;
pub mod routes;
pub mod startup;
pub mod telemetry;
